
const Digimon = [

      {
        name:"poyomon",
        family:"poyomon",
        data:0,
        combo:true,
        still:"src/digimon/poyomon.png",
        close:"src/digimon/poyomonC.jpg",
        found:true,
        live:"src/digimon/poyomon.gif",
        threeD:"src/digimon/poyomon3d.png",
        attribute:"water",
        level:0,
        training:[
          {
          type:"bird",
          exp:0
        },
        {
          type:"light",
          exp:0
        },
        {
          type:"dark",
          exp:0
        },
        {
          type:"beast",
          exp:0
        },
        {
          type:"dragon",
          exp:0
        },
        {
          type:"machine",
          exp:0
        },{
          type:"water",
          exp:0
        },{
          type:"plant",
          exp:0
        }
      ],
        movepool:[],

        moves:["bubble"],
        status:"baby",
        digivolve:["gomamon"],
        requirements:null,
        stats:{
          hp:40,
        defense:0,
        attack:10,
        speed:2,
        spirit:9
      }
      },

        {
          name:"gomamon",
          family:"poyomon",
          still:"src/digimon/gomamon.png",
          found:true,
          live:"src/digimon/gomamon.gif",
          threeD:"src/digimon/gomamon3d.png",
          close:"src/digimon/gomamonC.jpg",
          attribute:"water",
          moves:["call of the sea","scratch"],
          status:"rookie",
          from:"poyomon",
          digivolve:["ikkakumon","gesomon"],
          requirements:{
            level:9,
            battles:0,
            exp:null,
            digimon:"poyomon"
          },
        stats:{
          hp:60,
          defense:30,
          attack:20,
          speed:10,
          spirit:9
        }
        },
        {
          name:"gesomon",
          family:"poyomon",
          still:"src/digimon/gesomon.png",
            found:true,
          live:"src/digimon/gesomon.gif",
          threeD:"src/digimon/gesomon3d.png",
          close:"src/digimon/gesomonC.jpg",
          attribute:"water",
          moves:["ink swamp","ice crash"],
          status:"champion",
          from:"gomamon",
          digivolve:["whalemon"],
          requirements:{
            level:22,
            battles:12,
            exp:"dark",
            digimon:"gomamon"
          },
        stats:{
          hp:100,
          defense:29,
          attack:30,
          speed:30,
          spirit:3}
        },
        {
          name:"ikkakumon",
          family:"poyomon",
          still:"src/digimon/ikkakumon.png",
            found:true,
          live:"src/digimon/ikkakumon.gif",
          threeD:"src/digimon/ikkakumon3d.png",
          close:"src/digimon/gesomonC.jpg",
          attribute:"water",
          moves:["harpoon torpedo","ice crash"],
          status:"champion",
          from:"gomamon",
          digivolve:["zudomon"],
          requirements:{
            level:24,
            battles:0,
            exp:null,
            digimon:"gomamon"
          },
          stats:{
          hp:110,
          defense:32,
          attack:41,
          speed:19,
          spirit:19}
        },
        {
          name:"zudomon",
          family:"poyomon",
          still:"src/digimon/zudomon.png",
            found:true,
          live:"digimon/zudomon.png",
          threeD:"src/digimon/zudomon3d.png",
          close:"src/digimon/zudomonC.jpg",
          attribute:"water",
          moves:["thor hammer","ice crash"],
          status:"ultra",
          from:'ikkakumon',
          digivolve:["vikemon"],
          requirements:{
            level:30,
            battles:15,
            exp:null,
            digimon:"ikkakumon"
          },
          stats:{
            hp:190,
          defense:80,
          attack:51,
          speed:30,
          spirit:19
        }
        },
        {
          name:"whalemon",
          family:"poyomon",
          still:"src/digimon/whalemon.png",
            found:true,
          live:"src/digimon/whalemon.gif",
          threeD:"src/digimon/whalemon3d.png",
          close:"src/digimon/whalemonC.jpg",
          attribute:"water",
          from:"gesomon",
          moves:["whale chomp","whirlpool"],
          status:"ultra",
          digivolve:["zudomon"],
          requirements:{
            level:29,
            battles:0,
            exp:"water",
            digimon:"gesomon"
          },
          stats:{
            hp:240,
          defense:34,
          attack:51,
          speed:30,
          spirit:20}
        },
        {
          name:"vikemon",
          family:"poyomon",
          still:"src/digimon/vikemon.png",
          live:"src/digimon/vikemon.gif",
          threeD:"src/digimon/vikemon3d.png",
          close:"src/digimon/vikemonC.jpg",
          attribute:"water",

          moves:["god of thunder","ice age"],
          status:"mega",
          from:"zudomon",
          digivolve:null,
          requirements:{
            level:50,
            battles:30,
            exp:null,
            digimon:"zudomon"
          },
          stats:{
          hp:215,
          defense:99,
          attack:90,
          speed:49,
          spirit:52}
        },
        {
          name:"leviamon",
          family:"poyomon",
          still:"src/digimon/leviamon.png",
          live:"src/digimon/leviamon.gif",
          close:"src/digimon/leviamonC.jpg",
          found:false,
          threeD:"src/digimon/leviamon3d.png",
          attribute:"water",
          moves:["envious shadow","dark claw"],
          status:"mega",
          from:"whalemon",
          digivolve:[null],
          requirements:{
            level:67,
            battles:100,
            exp:"dark",
            digimon:"whalemon"
          },
          stats:{
          hp:500,
          defense:37,
          attack:117,
          speed:27,
          spirit:7
        }
      },
      {
        name:"kapurimon",
        family:"kapurimon",
        combo:false,
        still:"src/digimon/kapurimon.png",
       found:true,
      live:"src/digimon/kapurimon.gif",
      threeD:"src/digimon/kapurimon3d.png",
      close:"src/digimon/kapurimonC.jpg",
      attribute:"metal",
      moves:["bubble"],
       status:"baby",
       digivolve:["toyagumon"],
         requirements:null,
         stats:{
           hp:20,
         defense:0,
         attack:5,
         speed:5,
        spirit:3
      }
    },
    {
        name:"toyagumon",
        family:"kapurimon",
        still:"src/digimon/toyagumon.png",
        found:true,
        live:"src/digimon/toyagumon.gif",
        threeD:"src/digimon/toyagumon3d.png",
        close:"src/digimon/toyagumonC.jpg",
        attribute:"metal",
        moves:["fire breath","scratch"],
        status:"rookie",
        from:"kapurimon",
        digivolve:["ikkakumon","gesomon"],
        requirements:{
          level:12,
          battles:0,
          exp:null,
          digimon:"kapurimon"
        },
        stats:{
          hp:40,
        defense:10,
        attack:30,
        speed:20,
       spirit:3
     }
   },
     {
       name:"clockmon",
       family:"kapurimon",
       still:"src/digimon/clockmon.png",
       found:true,
       live:"src/digimon/clockmon.gif",
       threeD:"src/digimon/clockmon3d.png",
       close:"src/digimon/clockmonC.jpg",
       attribute:"metal",
       moves:["time warp","chrome smash","charge"],
       status:"champion",
       from:"toyagumon",
       digivolve:["cyberdramon"],
       requirements:{
         level:19,
         battles:10,
         exp:"metal",
         digimon:"toyagumon"
       },
     stats:{
        hp:100,
       defense:37,
       attack:28,
       speed:34,
       spirit:6
     }
   },
   {
       name:"cyberdramon",
       family:"kapurimon",
       still:"src/digimon/cyberdramon.png",
       found:true,
       live:"src/digimon/cyberdramon.gif",
       threeD:"src/digimon/cyberdramon3d.png",
       close:"src/digimon/cyberdramonC.jpg",
       attribute:"metal",
       moves:["cyber dash","chrome smash"],
       status:"ultra",
       from:"clockmon",
       digivolve:["darkdramon"],
       requirements:{
         level:40,
         battles:20,
         exp:"dragon",
         digimon:"clockmon"
       },
       stats:{
       hp:150,
       defense:56,
       attack:80,
       speed:109,
       spirit:30
     }
   },
   {
       name:"darkdramon",
       family:"kapurimon",
       still:"src/digimon/darkdramon.png",
       found:true,
       live:"digimon/darkdramon.gif",
       threeD:"src/digimon/darkdramon3d.png",
       close:"src/digimon/darkdramonC.jpg",
       attribute:"dragon",
       moves:["dragon roar","shadow rave"],
       status:"mega",
       from:'cyberdramon',
       digivolve:null,
       requirements:{
         level:67,
         battles:50,
         exp:"dark",
         digimon:"cyberdramon"
       },
       stats:{
         hp:50,
         defense:100,
         attack:310,
         speed:130,
         spirit:4
}
},
{
    name:"botamon",
    family:"botamon",
    still:"src/digimon/botamon.png",
    combo:false,
    level:1,
    training:[
      {
      type:"bird",
      exp:0
    },
    {
      type:"light",
      exp:0
    },
    {
      type:"dark",
      exp:0
    },
    {
      type:"beast",
      exp:0
    },
    {
      type:"dragon",
      exp:0
    },
    {
      type:"machine",
      exp:0
    },{
      type:"water",
      exp:0
    },{
      type:"plant",
      exp:0
    }
  ],
    movepool:[],
    data:0,
    found:true,
    live:"src/digimon/botamon.gif",
    threeD:"src/digimon/botamon.png",
    close:"src/digimon/botamonC.jpg",
    attribute:"dragon",
    moves:["bubble"],
    status:"baby",
    from:null,
    digivolve:["blackagumon"],
    requirements:null,
    stats:{
      hp:40,
      defense:7,
      attack:3,
      speed:9,
      spirit:4
}
},
{
    name:"blackagumon",
    family:"botamon",
    still:"src/digimon/blackagumon.png",
    found:true,
    live:"digimon/blackagumon.gif",
    threeD:"src/digimon/blackagumon3d.png",
    close:"src/digimon/blackagumonC.jpg",
    attribute:"dragon",
    moves:["pepper breath","scratch"],
    status:"rookie",
    from:"botamon",
    digivolve:["greymon","geogreymon"],
    requirements:{
      level:12,
      battles:10,
      exp:"dark",
      digimon:"botamon"
    },
    stats:{
      hp:20,
      defense:9,
      attack:18,
      speed:20,
      spirit:10
}
},
{
    name:"darktyrannomon",
    family:"botamon",
    still:"src/digimon/darktyrannomon.png",
    found:true,
    live:"digimon/blacktyrannomon.gif",
    threeD:"src/digimon/darktyrannomon3d.png",
    close:"src/digimon/darktyrannomonC.jpg",
    attribute:"dragon",
    moves:["fire storm"],
    status:"champion",
    from:"blackagumon",
    digivolve:["skullgreymon"],
    requirements:{
      level:24,
      battles:20,
      exp:"dark",
      digimon:"blackagumon"
    },
    stats:{
      hp:90,
      defense:21,
      attack:39,
      speed:25,
      spirit:10
}
},
{
    name:"skullgreymon",
    family:"botamon",
    still:"src/digimon/skullgreymon.png",
    found:true,
    live:"digimon/skullgreymon.gif",
    threeD:"src/digimon/skullgreymon3d.png",
    close:"src/digimon/skullgreymonC.jpg",
    attribute:"dragon",
    moves:["rocket launch"],
    status:"ultra",
    from:"blacktyrannomon",
    digivolve:["machinedramon"],
    requirements:{
      level:54,
      battles:30,
      exp:"dark",
      digimon:"blacktyrannomon"
    },
    stats:{
      hp:150,
      defense:50,
      attack:89,
      speed:35,
      spirit:10
}
},
{
    name:"machinedramon",
    family:"botamon",
    still:"src/digimon/machinedramon.png",
    found:true,
    live:"digimon/machinedramon.gif",
    threeD:"src/digimon/machinedramon3d.png",
    close:"src/digimon/machinedramonC.jpg",
    attribute:"metal",
    moves:["giga cannon"],
    status:"mega",
    from:"skullgreymon",
    digivolve:null,
    requirements:{
      level:99,
      battles:50,
      exp:"metal",
      digimon:"skullgreymon"
    },
    stats:{
      hp:180,
      defense:181,
      attack:159,
      speed:60,
      spirit:32
}
},
{
    name:"poromon",
    family:"poromon",
    combo:false,
    still:"src/digimon/poromon.png",
    found:true,
    live:"digimon/poromon.gif",
    threeD:"src/digimon/poromon3d.png",
    close:"src/digimon/poromonC.jpg",
    attribute:"bird",
    moves:["bubble"],
    status:"baby",
    from:null,
    digivolve:["biyomon"],
    requirements:null,
    stats:{
      hp:40,
      defense:4,
      attack:9,
      speed:17,
      spirit:12
}
},
{
    name:"biyomon",
    family:"poromon",
    still:"src/digimon/biyomon.png",
    found:true,
    live:"digimon/biyomon.gif",
    threeD:"src/digimon/biyomon3d.png",
    close:"src/digimon/biyomonC.jpg",
    attribute:"bird",
    moves:["spiral beak"],
    status:"rookie",
    from:"poromon",
    digivolve:['birdramon'],
    requirements:{
      level:12,
      battles:5,
      exp:null,
      digimon:"poromon"
    },
    stats:{
      hp:49,
      defense:21,
      attack:21,
      speed:21,
      spirit:21
}
},
{
    name:"birdramon",
    family:"poromon",
    still:"src/digimon/birdramon.png",
    found:true,
    live:"digimon/birdramon.gif",
    threeD:"src/digimon/birdramon3d.png",
    close:"src/digimon/birdramonC.jpg",
    attribute:"bird",
    moves:["phoenix flame"],
    status:"champion",
    from:"biyomon",
    digivolve:["garudamon"],
    requirements:{
      level:30,
      battles:null,
      digimon:"biyomon",
      exp:"bird",
    },
    stats:{
      hp:120,
      defense:50,
      attack:45,
      speed:54,
      spirit:34
}
},
{
    name:"garudamon",
    family:"poromon",
    still:"src/digimon/garudamon.png",
    found:true,
    live:"digimon/garudamon.gif",
    threeD:"src/digimon/garudamon3d.png",
    close:"src/digimon/garudamonC.jpg",
    attribute:"bird",
    moves:["phoenix flame","sky attack"],
    status:"ultra",
    from:"birdramon",
    digivolve:["phoenixmon"],
    requirements:{
      level:40,
      battles:21,
      digimon:"birdramon",
      exp:"bird",
    },
    stats:{
      hp:200,
      defense:90,
      attack:100,
      speed:60,
      spirit:40
}
},
{
    name:"phoenixmon",
    family:"poromon",
    still:"src/digimon/phoenixmon.png",
    found:true,
    live:"digimon/phoenixmon.gif",
    threeD:"src/digimon/phoenixmon3d.png",
    close:"src/digimon/phoenixmonC.jpg",
    attribute:"bird",
    moves:["rays from above","phoenix blast"],
    status:"mega",
    from:"garudamon",
    digivolve:null,
    requirements:{
      level:78,
      battles:40,
      exp:"bird",
      digimon:"garudamon"
    },
    stats:{
      hp:176,
      defense:56,
      attack:118,
      speed:154,
      spirit:70
}
},
{
    name:"tokomon",
    family:"tokomon",
    combo:false,
    still:"src/digimon/tokomon.png",
    animation:["tokomon1.png","tokomon2.png","tokomon3.png"],
    found:true,
    live:"src/digimon/tokomon.gif",
    threeD:"src/digimon/tokomon.png",
    close:"src/digimon/tokomonC.jpg",
    attribute:"bird",
    level:1,
    training:[
      {
      type:"bird",
      exp:0
    },
    {
      type:"light",
      exp:0
    },
    {
      type:"dark",
      exp:0
    },
    {
      type:"beast",
      exp:0
    },
    {
      type:"dragon",
      exp:0
    },
    {
      type:"machine",
      exp:0
    },{
      type:"water",
      exp:0
    },{
      type:"plant",
      exp:0
    }
  ],
    data:0,
    movepool:[],
    moves:["bubble"],
    status:"baby",
    from:null,
    digivolve:["patamon"],
    requirements:null,
    stats:{
      hp:10,
      defense:4,
      attack:5,
      speed:8,
      spirit:12
}
},
{
    name:"patamon",
    family:"tokomon",
    still:"src/digimon/patamon.png",
    animation:["patamon1.png","patamon2.png","patamon3.png"],
    found:true,
    live:"digimon/patamon.gif",
    threeD:"src/digimon/patamon3d.png",
    close:"src/digimon/patamonC.jpg",
    attribute:"bird",
    moves:["gust"],
    status:"rookie",
    from:"tokomon",
    digivolve:["angemon"],
    requirements:{
      level:9,
      battles:5,
      exp:"light",
      digimon:"tokomon"
    },
    stats:{
      hp:30,
      defense:21,
      attack:29,
      speed:44,
      spirit:22
}
},
{
    name:"angemon",
    family:"tokomon",
    still:"src/digimon/angemon.png",
    found:true,
    live:"digimon/angemon.gif",
    threeD:"src/digimon/angemon3d.png",
    close:"src/digimon/angemonC.jpg",
    attribute:"light",
    moves:["hand of fate"],
    status:"champion",
    from:"patamon",
    digivolve:["magnangemon"],
    requirements:{
      level:21,
      battles:40,
      exp:"light",
      digimon:"patamon"
    },
    stats:{
      hp:90,
      defense:45,
      attack:45,
      speed:60,
      spirit:48
}
},
{
    name:"magnangemon",
    family:"tokomon",
    still:"src/digimon/magnangemon.png",
    found:true,
    live:"digimon/magnangemon.gif",
    threeD:"src/digimon/magnangemon3d.png",
    close:"src/digimon/magnangemonC.jpg",
    attribute:"light",
    moves:["sword of fate"],
    status:"ultra",
    from:"angemon",
    digivolve:["seriphmon"],
    requirements:{
      level:32,
      battles:50,
      exp:"light",
      digimon:"angemon"
    },
    stats:{
      hp:230,
      defense:80,
      attack:74,
      speed:98,
      spirit:60
}
},
{
    name:"seriphmon",
    family:"tokomon",
    still:"src/digimon/seriphmon.png",
    found:true,
    live:"digimon/seriphmon.gif",
    threeD:"src/digimon/seriphmon3d.png",
    close:"src/digimon/seriphmonC.jpg",
    attribute:"light",
    moves:["ray of hope"],
    status:"mega",
    from:"magnangemon",
    digivolve:null,
    requirements:{
      level:52,
      battles:60,
      exp:"light",
      digimon:"magnangemon"
    },
    stats:{
      hp:200,
      defense:120,
      attack:94,
      speed:88,
      spirit:120
}
},
{
    name:"gabumon",
    family:"tsunomon",
    animation:["gabumon1.png","gabumon2.png","gabumon3.png"],
    still:"src/digimon/gabumon.png",
    found:true,
    live:"digimon/gabumon.gif",
    threeD:"src/digimon/gabumon3d.png",
    close:"src/digimon/gabumonC.jpg",
    attribute:"beast",
    moves:["rainbow scratch","scratch"],
    status:"rookie",
    from:"tsunomon",
    digivolve:["garurumon","blackgarurumon"],
    requirements:{
      level:10,
      battles:12,
      exp:"beast",
      digimon:"tsunomon"
    },
    stats:{
      hp:32,
      defense:28,
      attack:28,
      speed:27,
      spirit:29
    }
},
{
    name:"blackgabumon",
    family:"tsunomon",
    still:"src/digimon/blackgabumon.png",
    found:true,
    live:"digimon/blackgabumon.gif",
    threeD:"src/digimon/blackgabumon3d.png",
    close:"src/digimon/blackgabumonC.jpg",
    attribute:"beast",
    moves:["bubble"],
    status:"baby",
    from:null,
    digivolve:["blackgarurumon"],
    requirements:{
      level:12,
      battles:12,
      exp:"dark",
      digimon:"tsunomon"
    },
    stats:{
      hp:32,
      defense:18,
      attack:38,
      speed:27,
      spirit:19
    }
},
{
    name:"garurumon",
    family:"tsunomon",

    still:"src/digimon/garurumon.png",
    found:true,
    live:"digimon/garurumon.gif",
    threeD:"src/digimon/garurumon3d.png",
    close:"src/digimon/garurumonC.jpg",
    attribute:"beast",
    moves:["ice breath","scratch"],
    status:"champion",
    from:"gabumon",
    digivolve:["weregarurumon"],
    requirements:{
      level:10,
      battles:12,
      exp:"beast",
      digimon:"gabumon"
    },
    stats:{
      hp:52,
      defense:58,
      attack:58,
      speed:57,
      spirit:39
    }
},
{
    name:"blackgarurumon",
    family:"tsunomon",
    still:"src/digimon/blackgarurumon.png",
    found:true,
    live:"src/digimon/blackgabumon.gif",
    threeD:"src/digimon/blackgarurumon3d.png",
    close:"src/digimon/blackgarurumonC.jpg",
    attribute:"beast",
    moves:["shadow breath"],
    status:"champion",
    from:'blackgabumon',
    digivolve:["blackweregarurumon"],
    requirements:{
      level:32,
      battles:12,
      exp:"dark",
      digimon:'blackgabumon'
    },
    stats:{
      hp:42,
      defense:28,
      attack:68,
      speed:47,
      spirit:19
    }
},
{
    name:"blackweregarurumon",
    family:"tsunomon",
    still:"src/digimon/blackweregarurumon.png",
    found:true,
    live:"src/digimon/blackgabumon.gif",
    threeD:"src/digimon/blackweregarurumon3d.png",
        close:"src/digimon/blackweregarurumonC.jpg",
    attribute:"beast",
    moves:["jungle ambush","shadow breath"],
    status:"ultra",
    from:null,
    digivolve:["blackmetalgarurumon"],
    requirements:{
      level:52,
      battles:12,
      exp:"dark",
      digimon:"blackgarurumon"
    },
    stats:{
      hp:62,
      defense:78,
      attack:88,
      speed:77,
      spirit:19
    }
},
{
    name:"weregarurumon",
    family:"tsunomon",
    still:"src/digimon/weregarurumon.png",
    found:true,
    live:"src/digimon/weregarurumon.gif",
    threeD:"src/digimon/weregarurumon3d.png",
        close:"src/digimon/weregarurumonC.jpg",
    attribute:"beast",
    moves:["ice punch"],
    status:"ultra",
    from:null,
    digivolve:["metalgarurumon"],
    requirements:{
      level:52,
      battles:52,
      exp:"beast",
      digimon:"garurumon"
    },
    stats:{
      hp:72,
      defense:78,
      attack:78,
      speed:97,
      spirit:39
    }
},
{
    name:"blackmetalgarurumon",
    family:"tsunomon",
    still:"src/digimon/blackmetalgarurumon.png",
    found:true,
    live:"src/digimon/blackmetalgarurumon.gif",
    threeD:"src/digimon/blackmetalgarurumon3d.png",
        close:"src/digimon/blackmetalgarurumonC.jpg",
    attribute:"beast",
    moves:["shadow arsenal","napalm"],
    status:"mega",
    from:"blackweregarurumon",
    digivolve:null,
    requirements:{
      level:60,
      battles:62,
      exp:"dark",
      digimon:"blackweregarurumon"
    },
    stats:{
      hp:92,
      defense:108,
      attack:128,
      speed:117,
      spirit:89
    }
},
{
    name:"metalgarurumon",
    family:"tsunomon",
    still:"src/digimon/metalgarurumon.png",
    found:true,
    live:"src/digimon/metalgarurumon.gif",
    threeD:"src/digimon/metalgarurumon3d.png",
        close:"src/digimon/metalgarurumonC.jpg",
    attribute:"beast",
    moves:["future arsenal","napalm"],
    status:"mega",
    from:null,
    digivolve:null,
    requirements:{
      level:82,
      battles:72,
      exp:"beast",
      digimon:"weregarurumon"
    },
    stats:{
      hp:102,
      defense:168,
      attack:108,
      speed:107,
      spirit:180
    }
},
{
    name:"tsunomon",
    family:"tsunomon",
    animation:["tsunomon1.png","tsunomon2.png","tsunomon3.png"],
    combo:true,
    still:"src/digimon/tsunomon.png",
    found:true,
    live:"src/digimon/tsunomon.gif",
    threeD:"src/digimon/tsunomon3d.png",
    close:"src/digimon/tsunomonC.jpg",
    attribute:"beast",
    moves:["bubble"],
    status:"baby",
    from:null,
    digivolve:["gabumon"],
    requirements:null,
    stats:{
      hp:12,
      defense:8,
      attack:8,
      speed:7,
      spirit:9
    }
}

    ]


module.exports = Digimon;
