const Test = [

    {
      question:"What is your name?",
      answer:{
        type:"input",
        choices:null
      }
    },
    {
      question:"Are you a boy or girl?",
      answer:{
        type:"gender",
        choices:[{
          word:"Boy",
          class:"bbm nn"
        },
        {
          word:"Girl",
          class:"rbbm nn"
        }
      ]
      }
    },
    {
      question:"Choose your starter digimon",
      answer:{
        type:"choices",
        choices: [{
          name:"poyomon",
          family:"poyomon",
          data:0,
          combo:true,
          still:"./../digimon/poyomon.png",
          close:"./../digimon/poyomonC.jpg",
          found:true,
          live:"./../digimon/poyomon.gif",
          threeD:"./../digimon/poyomon3d.png",
          attribute:"water",
          level:0,
          training:[
            {
            type:"bird",
            exp:0
          },
          {
            type:"light",
            exp:0
          },
          {
            type:"dark",
            exp:0
          },
          {
            type:"beast",
            exp:0
          },
          {
            type:"dragon",
            exp:0
          },
          {
            type:"machine",
            exp:0
          },{
            type:"water",
            exp:0
          },{
            type:"plant",
            exp:0
          }
        ],
          movepool:[],

          moves:["bubble"],
          status:"baby",
          digivolve:["gomamon"],
          requirements:null,
          stats:{
            hp:40,
          defense:0,
          attack:10,
          speed:2,
          spirit:9
        }
        },
        {
            name:"botamon",
            family:"botamon",
            still:"./../digimon/botamon.png",
            combo:false,
            level:1,
            training:[
              {
              type:"bird",
              exp:0
            },
            {
              type:"light",
              exp:0
            },
            {
              type:"dark",
              exp:0
            },
            {
              type:"beast",
              exp:0
            },
            {
              type:"dragon",
              exp:0
            },
            {
              type:"machine",
              exp:0
            },{
              type:"water",
              exp:0
            },{
              type:"plant",
              exp:0
            }
          ],
            movepool:[],
            data:0,
            found:true,
            live:"./../digimon/botamon.gif",
            threeD:"./../digimon/botamon.png",
            close:"./../digimon/botamonC.jpg",
            attribute:"dragon",
            moves:["bubble"],
            status:"baby",
            from:null,
            digivolve:["blackagumon"],
            requirements:null,
            stats:{
              hp:40,
              defense:7,
              attack:3,
              speed:9,
              spirit:4
        }
        },
        {
            name:"tokomon",
            family:"tokomon",
            combo:false,
            still:"./../digimon/tokomon.png",
            animation:["tokomon1.png","tokomon2.png","tokomon3.png"],
            found:true,
            live:"./../digimon/tokomon.gif",
            threeD:"./../digimon/tokomon.png",
            close:"./../digimon/tokomonC.jpg",
            attribute:"bird",
            level:1,
            training:[
              {
              type:"bird",
              exp:0
            },
            {
              type:"light",
              exp:0
            },
            {
              type:"dark",
              exp:0
            },
            {
              type:"beast",
              exp:0
            },
            {
              type:"dragon",
              exp:0
            },
            {
              type:"machine",
              exp:0
            },{
              type:"water",
              exp:0
            },{
              type:"plant",
              exp:0
            }
          ],
            data:0,
            movepool:[],
            moves:["bubble"],
            status:"baby",
            from:null,
            digivolve:["patamon"],
            requirements:null,
            stats:{
              hp:10,
              defense:4,
              attack:5,
              speed:8,
              spirit:12
        }
        }
      ]
      }
    },
  ]


module.exports = Test;
